Feature/add invert effect
uploadcare/uploadcare-widget-tab-effects pull request #10
Opened 2018-03-27 08:22 UTC by bautrukevich

По сути вернул то, что было.

2018-03-27 08:24 UTC, bautrukevich commented
![](https://github.trello.services/images/mini-trello-icon.png) [Effects tab: вернуть invert](https://trello.com/c/X1Po6F7O/292-effects-tab-%D0%B2%D0%B5%D1%80%D0%BD%D1%83%D1%82%D1%8C-invert)

2018-03-29 12:49 UTC, nd0ut approved these changes

2018-04-04 07:34 UTC, Zmoki requested changes
Всё отлично, но нужно поменять svg

2018-04-04 07:34 UTC, Zmoki commented on src/images/invert.svg
> +</svg>
Поменяй на

```
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" xmlns:xlink="http://www.w3.org/1999/xlink">
  <path d="M5,6.99180311 C5,5.89386312 5.90087297,5 6.99180311,5 L25.0081969,5 C26.1061369,5 27,5.90087297 27,6.99180311 L27,25.0081969 C27,26.1061369 26.099127,27 25.0081969,27 L6.99180311,27 C5.89386312,27 5,26.099127 5,25.0081969 L5,6.99180311 Z M25,7 L7,7 L7,25 L12.071629,19.928371 C13.0769868,20.9337288 14.4658757,21.5555556 16,21.5555556 C19.0682486,21.5555556 21.5555556,19.0682486 21.5555556,16 C21.5555556,14.4658757 20.9337288,13.0769868 19.928371,12.071629 L25,7 L25,7 Z M12.071629,19.928371 C11.0662712,18.9230132 10.4444444,17.5341243 10.4444444,16 C10.4444444,12.9317514 12.9317514,10.4444444 16,10.4444444 C17.5341243,10.4444444 18.9230132,11.0662712 19.928371,12.071629 L12.071629,19.928371 L12.071629,19.928371 Z"/>
</svg>
```

2018-04-04 07:47 UTC, bautrukevich commented on src/images/invert.svg
> +</svg>
Done! : )

2018-04-04 07:54 UTC, Zmoki approved these changes

2018-04-05 13:30 UTC, merged