Force crop when crop preset is set
uploadcare/uploadcare-widget-tab-effects pull request #13
Opened 2018-04-03 13:52 UTC by nd0ut

2018-04-03 14:17 UTC, nd0ut commented
![](https://github.trello.services/images/mini-trello-icon.png) [Effects tab: сделать возможность форсить кроппинг, если заданы его параметры.](https://trello.com/c/CmzfhjUH/65-effects-tab-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%84%D0%BE%D1%80%D1%81%D0%B8%D1%82%D1%8C-%D0%BA%D1%80%D0%BE%D0%BF%D0%BF%D0%B8%D0%BD%D0%B3-%D0%B5%D1%81%D0%BB%D0%B8-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D1%8B-%D0%B5%D0%B3%D0%BE-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B)

2018-04-04 04:59 UTC, bautrukevich approved these changes

2018-04-16 06:51 UTC, nd0ut commented
![](https://github.trello.services/images/mini-trello-icon.png) [Effects tab: сделать возможность форсить кроппинг, если заданы его параметры.](https://trello.com/c/CmzfhjUH/65-effects-tab-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%84%D0%BE%D1%80%D1%81%D0%B8%D1%82%D1%8C-%D0%BA%D1%80%D0%BE%D0%BF%D0%BF%D0%B8%D0%BD%D0%B3-%D0%B5%D1%81%D0%BB%D0%B8-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D1%8B-%D0%B5%D0%B3%D0%BE-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B)

2018-04-17 07:44 UTC, Zmoki requested changes
```
🚨   Error: 'autoCrop' is not exported by src\tools\index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\create-preview-tab-effects.js (1:47)
1: import { customExtends, configureTranslations, autoCrop } from 'tools';
```

Добавь автокроп в tools/index.js

2018-04-17 07:50 UTC, nd0ut commented
@Zmoki сори, `tools.js` не закоммитил

2018-04-17 19:51 UTC, Zmoki approved these changes

2018-04-17 20:05 UTC, merged