Unset applied effects in crop mode.
uploadcare/uploadcare-widget-tab-effects pull request #16
Opened 2018-04-11 13:05 UTC by bautrukevich

2018-04-11 13:06 UTC, bautrukevich commented
![](https://github.trello.services/images/mini-trello-icon.png) [Effects tab: в режиме кропа показывать изображение без всех применённых эффектов](https://trello.com/c/d4joswrL/64-effects-tab-%D0%B2-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B5-%D0%BA%D1%80%D0%BE%D0%BF%D0%B0-%D0%BF%D0%BE%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B5%D0%B7-%D0%B2%D1%81%D0%B5%D1%85-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%91%D0%BD%D0%BD%D1%8B%D1%85-%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82%D0%BE%D0%B2)

2018-04-17 08:31 UTC, Zmoki commented on package.json
> +    "babel-helper-function-name": "^6.24.1",
зачем этот хелпер?

2018-04-17 08:34 UTC, bautrukevich commented on package.json
> +    "babel-helper-function-name": "^6.24.1",
Без него ругается сборка почему-то, пишет что его не хватает. Хотя сейчас уже и не вспомню точно.

2018-04-17 08:55 UTC, Zmoki commented on package.json
> +    "babel-helper-function-name": "^6.24.1",
сейчас проверила, всё ок, он не нужен. странная фигня. удали его

2018-04-17 15:31 UTC, bautrukevich commented on package.json
> +    "babel-helper-function-name": "^6.24.1",
Да и правда, странное что-то было. Удалил.

2018-04-17 19:45 UTC, Zmoki requested changes
I need to revert changes in package-lock too

2018-04-17 20:00 UTC, Zmoki approved these changes

2018-04-17 20:01 UTC, merged