Fix locales and add fallback if locale doesn't exists
uploadcare/uploadcare-widget-tab-effects pull request #29
Opened 2019-02-13 09:30 UTC by bautrukevich

2019-02-13 09:31 UTC, bautrukevich commented
![](https://github.trello.services/images/mini-trello-icon.png) [Effects Tab: Не работает fallback на en и не отображаются тултипы остальных локалей (кроме ru, en, fr)](https://trello.com/c/eUO4HWHZ/504-effects-tab-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-fallback-%D0%BD%D0%B0-en-%D0%B8-%D0%BD%D0%B5-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%8E%D1%82%D1%81%D1%8F-%D1%82%D1%83%D0%BB%D1%82%D0%B8%D0%BF%D1%8B-%D0%BE%D1%81%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B5%D0%B9-%D0%BA%D1%80%D0%BE%D0%BC%D0%B5-ru-en-fr)

2019-02-13 13:23 UTC, nd0ut requested changes

2019-02-13 13:23 UTC, nd0ut commented on src/tools/configure-translations.js
>    let newTranslations = {...translations}
```suggestion
  const newTranslations = {...translations}
```

2019-02-13 13:55 UTC, Zmoki requested changes

2019-02-13 13:55 UTC, Zmoki commented on src/create-preview-tab-effects.js
> +        }
You totally rewrite locale for the preview tab with `en`. You need to use the `en` locale for effects only if custom locale doesn‘t exist in Effects Tab.

Preview tab without Effects Tab on Poland:
<img width="600" alt="2019-02-13 16 48 09" src="https://user-images.githubusercontent.com/948688/52716397-b7be6000-2faf-11e9-8d15-027dba158a7e.png">

Preview tab with Effects Tab on Poland (title and main buttons on english too):
<img width="600" alt="2019-02-13 16 48 45" src="https://user-images.githubusercontent.com/948688/52716430-cc9af380-2faf-11e9-858e-485a89e23d43.png">

2019-02-13 13:55 UTC, Zmoki commented on src/locale/index.js
> +  vi,
Oops, I missed it before. Thank you!

2019-02-14 14:54 UTC, Zmoki approved these changes

2019-02-18 07:58 UTC, nd0ut approved these changes

2019-02-18 19:18 UTC, merged